---
- name: Install ELK, Nagios, (Grafana, Prometheus, Influxdb) in Ubuntu
  become: true
  hosts: Ubuntu
  roles:
    - elk_ubuntu
    - nagios_ubuntu
    - grafana_ubuntu
    - prometheus_ubuntu
    - influxdb_ubuntu
#    - mariadb_ubuntu


- name: Install ELK, (Grafana, Prometheus, Influxdb), LAMP in CentOS
  become: true
  hosts: CentOS
  roles:
    - elk_centos
    - influxdb_centos
    - grafana_centos
    - prometheus_centos
    - mariadb_centos

- name: Install Httpd + Php on both systems
  become: true
  hosts: all
  roles:
    - httpd

