---
# vars file for influxdb_centos

# Version of influxdb you want to install
INFLUXDB_RPM_FILENAME: 'influxdb-0.9.6.1-1.x86_64.rpm'

# Password for your InfluxDB root user
INFLUXDB_ROOT_PASSWORD: '321321'

# Database that will hold your project's metrics
INFLUXDB_DATABASE: 'project'

# User that will connect to above database
INFLUXDB_USER: 'project'

# Password for the above user
INFLUXDB_PASSWORD: 'project'

# Password for the grafana user who will connect to the grafana database
INFLUXDB_GRAFANA_PASSWORD: 'grafana'

# Version of grafana you want to install
GRAFANA_RPM_FILENAME: 'grafana-2.6.0-1.x86_64.rpm'

# Port for grafana nginx virtual server
# GRAFANA_NGINX_PORT: 8080

# Basic HTTP AUTH password for the grafana frontent (username is grafana)
# HTPASSWD_GRAFANA_PASSWORD: 'grafana'

# INFLUXDB endpoint (for collectd)
INFLUXDB_ADDRESS: '127.0.0.1'
