---
# tasks file for influxdb_centos

- name: Add gpg key
    command: sudo rpm --import https://repos.influxdata.com/influxdb.key

- name: Install influxdb
  dnf:
    name: influxdb2
    state: present

- name: influxdb - start service
  service: name=influxdb state=started

- name: influxdb - wait for service
  wait_for: port=8086 delay=2
