---
# tasks file for influxdb_centos

- name: Add influxdb GPG key.
  rpm_key:
    key: https://repos.influxdata.com/influxdb.key
    state: present

- name: Add repository for influxdb
  copy:
    src: influxdb.repo
    dest: /etc/yum.repos.d/

- name: Install influxdb
  dnf:
    name: influxdb2
    state: present

- name: influxdb - start service
  service: name=influxdb state=started

- name: influxdb - wait for service
  wait_for: port=8086 delay=2
