---
# tasks file for grafana_ubuntu

- name: Add key to grafana package
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Debian | Add repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: "grafana"


- name: update Ubuntu
  apt:
    upgrade: YES
    update_cache: YES

- name: install Grafana
  apt:
    name: grafana
    state: present

